/****************************************************************************\
 * Epic Classic Game
 * Author: Jose Daniel Amador Salas
 * This class is in charge of manage the hangman game
 * Create: 17/09/2018
 * Version: 1.0.
\****************************************************************************/
package codeapp.view;

public class Hangman extends javax.swing.JFrame {

    /**
     * Creates new form Hangman
     */
    public Hangman() {
        initComponents();
    }
    public Thread cronometro = new Thread(){
        @Override
        public void run(){
            int hour=0, min=0, seg=0;
            for(;;){
                try{
                    seg++;
                    if(seg>59){
                        seg=0;
                        min++;
                    }
                    if(min>59){
                        min=0;
                        hour++;
                    }
                    lblCrono.setText(hour+":"+min+":"+seg);
                    Thread.sleep(999);
                }
                catch(InterruptedException e){

                }
            }
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        pnWord = new javax.swing.JPanel();
        lblWord = new javax.swing.JLabel();
        pnLetters = new javax.swing.JPanel();
        btnNewGame = new javax.swing.JButton();
        btnAfter = new javax.swing.JButton();
        btnBefore = new javax.swing.JButton();
        lblCrono = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hangman Game");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codeapp/util/hangman/icon.png"))); // NOI18N
        getContentPane().add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 100, 100));

        jLabel1.setFont(new java.awt.Font("Hack", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 240));
        jLabel1.setText("Hangman Game");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 350, 70));

        btnBack.setBackground(new java.awt.Color(41, 42, 51));
        btnBack.setFont(new java.awt.Font("Hack", 3, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 60, 210, 40));

        lblWord.setFont(new java.awt.Font("Hack", 3, 48)); // NOI18N
        lblWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWord.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnWordLayout = new javax.swing.GroupLayout(pnWord);
        pnWord.setLayout(pnWordLayout);
        pnWordLayout.setHorizontalGroup(
            pnWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnWordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWord, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnWordLayout.setVerticalGroup(
            pnWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnWordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWord, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 1030, 90));

        pnLetters.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnLetters.setOpaque(false);

        javax.swing.GroupLayout pnLettersLayout = new javax.swing.GroupLayout(pnLetters);
        pnLetters.setLayout(pnLettersLayout);
        pnLettersLayout.setHorizontalGroup(
            pnLettersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
        );
        pnLettersLayout.setVerticalGroup(
            pnLettersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );

        getContentPane().add(pnLetters, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 720, 160));

        btnNewGame.setBackground(new java.awt.Color(38, 39, 44));
        btnNewGame.setFont(new java.awt.Font("Hack", 3, 24)); // NOI18N
        btnNewGame.setText("New Game");
        btnNewGame.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNewGame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(btnNewGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 210, 40));

        btnAfter.setFont(new java.awt.Font("Hack", 3, 14)); // NOI18N
        btnAfter.setText("+ Nivel");
        btnAfter.setToolTipText("masNivel");
        getContentPane().add(btnAfter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 180, -1, 90));

        btnBefore.setFont(new java.awt.Font("Hack", 3, 14)); // NOI18N
        btnBefore.setText("- Nivel");
        btnBefore.setToolTipText("menosNivel");
        getContentPane().add(btnBefore, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 90));

        lblCrono.setFont(new java.awt.Font("Hack", 3, 36)); // NOI18N
        lblCrono.setForeground(new java.awt.Color(254, 254, 254));
        lblCrono.setText("00:00:00");
        getContentPane().add(lblCrono, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 500, 200, 140));

        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codeapp/util/hangman/background.jpg"))); // NOI18N
        lblTitle.setToolTipText("");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hangman().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAfter;
    public javax.swing.JButton btnBack;
    public javax.swing.JButton btnBefore;
    public javax.swing.JButton btnNewGame;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblCrono;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblTitle;
    public javax.swing.JLabel lblWord;
    public javax.swing.JPanel pnLetters;
    public javax.swing.JPanel pnWord;
    // End of variables declaration//GEN-END:variables
}
