/****************************************************************************\
 * Epic Classic Game
 * Author: Jose Daniel Amador Salas
 * This class is in charge of manage the hangman game
 * Create: 17/09/2018
 * Version: 1.0.
\****************************************************************************/
package codeapp.view;

public class LettersSoup extends javax.swing.JFrame {

    /**
     * Creates new form WordsSoup
     */
    public LettersSoup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLetters = new javax.swing.JPanel();
        pnWords = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnNewGame = new javax.swing.JButton();
        btnAutoSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnLetters.setLayout(new java.awt.GridLayout(15, 15));
        getContentPane().add(pnLetters, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 650, 650));

        pnWords.setLayout(new java.awt.GridLayout(15, 2));
        getContentPane().add(pnWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 370, 540));

        jLabel2.setFont(new java.awt.Font("Hack", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Letter's Soup Game");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, -1));

        btnNewGame.setFont(new java.awt.Font("Hack", 3, 18)); // NOI18N
        btnNewGame.setText("New Game");
        getContentPane().add(btnNewGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 180, -1));

        btnAutoSave.setFont(new java.awt.Font("Hack", 3, 18)); // NOI18N
        btnAutoSave.setText("Auto Solve");
        getContentPane().add(btnAutoSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 110, 180, -1));

        btnBack.setFont(new java.awt.Font("Hack", 3, 18)); // NOI18N
        btnBack.setText("Back");
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 110, 140, -1));

        jLabel1.setFont(new java.awt.Font("Hack", 3, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codeapp/util/letters_soup/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LettersSoup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LettersSoup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LettersSoup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LettersSoup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LettersSoup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAutoSave;
    public javax.swing.JButton btnBack;
    public javax.swing.JButton btnNewGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JPanel pnLetters;
    public javax.swing.JPanel pnWords;
    // End of variables declaration//GEN-END:variables
}
